spring:
  application:
    name: licensing-service
  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8071"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/